# Generated by Django 4.1.3 on 2022-11-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Articulos',
        ),
    ]
